name: Midnight Publish

on:
  schedule:
    # 日本時間の深夜0時5分（UTCの15時5分）に毎日実行
    - cron: '5 15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
